name: Build coredns-kubenodes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:


permissions:
  id-token: write # required to use OIDC authentication
  contents: read

jobs:
  build-and-push:
    name: Build coredns-kubenodes and push to public ECR
    runs-on: ubuntu-latest
    steps:
      - name: Get repo name
        id: repoName
        run: echo "::set-output name=reponame::$(echo ${{github.repository}} | cut -d '/' -f 2)"
      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::645843940509:role/github-actions-ecr-public-create-read-write
          role-duration-seconds: 300 # 5 minutes should be enough for build-and-push
          aws-region: us-east-1
      # Using this until https://github.com/aws-actions/amazon-ecr-login/issues/116
      # is closed
      - name: Build and Push to ECR public
        id: build-and-push
        uses: pahud/ecr-public-action@0db8adbcfd3c3ec2f604d70fdd6b5d15c80e1dbc
        with:
          tags: |
            public.ecr.aws/e5r9m0c5/${{ steps.repoName.outputs.reponame }}:latest
            public.ecr.aws/e5r9m0c5/${{ steps.repoName.outputs.reponame }}:${{ steps.sha.outputs.sha7 }}
